apiVersion: apps/v1
kind: Deployment
metadata:
  name: falsk-D
  namespace: demo
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: 
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        env:
        - name: AWS_REGION
          value: "us-east-1"
        - name: AWS_ACCOUNT_ID
          value: "242201289959"
        - name: ECR_REPO
          value: "my-python-app"
        - name: IMAGE_NAME
          value: "my-python-app"
        - name: IMAGE_TAG
          value: "latest"
